pull_request_rules:
  - name: Squash and merge (one commit)
    conditions:
      - check-success=Build PhotoBroom sources on Linux (GNU, gcc-14, g++-14, Release, false, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on Linux (GNU, gcc-14, g++-14, Release, true, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on Linux (LLVM, clang, clang++, Release, false, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on Linux (LLVM, clang, clang++, Release, true, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on MacOS (macos-15)
      - check-success=Build PhotoBroom sources on MacOS (macos-26)
      - check-success=Unit tests coverage (ubuntu-24.04)
      - "#commits=1"
      - or:
        - "#approved-reviews-by>0"
        - author=Kicer86
    actions:
      merge:
        method: squash
      delete_head_branch:
        force: false

  - name: Merge pull request (more than one commit)
    conditions:
      - check-success=Build PhotoBroom sources on Linux (GNU, gcc-14, g++-14, Release, false, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on Linux (GNU, gcc-14, g++-14, Release, true, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on Linux (LLVM, clang, clang++, Release, false, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on Linux (LLVM, clang, clang++, Release, true, ubuntu-24.04)
      - check-success=Build PhotoBroom sources on MacOS (macos-15)
      - check-success=Build PhotoBroom sources on MacOS (macos-26)
      - check-success=Unit tests coverage (ubuntu-24.04)
      - "#commits>1"
      - "#commits-behind=0"
      - or:
        - "#approved-reviews-by>0"
        - author=Kicer86
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: false
