var searchData=
[
  ['ianalyzer_0',['IAnalyzer',['../dc/da7/struct_i_analyzer.html',1,'']]],
  ['ibackend_1',['IBackend',['../d2/ddd/struct_database_1_1_i_backend.html',1,'Database']]],
  ['ibuilder_2',['IBuilder',['../dc/d82/struct_database_1_1_i_builder.html',1,'Database']]],
  ['icompleterfactory_3',['ICompleterFactory',['../d1/d5c/struct_i_completer_factory.html',1,'']]],
  ['iconfigdialogmanager_4',['IConfigDialogManager',['../df/d60/struct_i_config_dialog_manager.html',1,'']]],
  ['iconfigstorage_5',['IConfigStorage',['../de/dfa/struct_i_config_storage.html',1,'']]],
  ['iconfigtab_6',['IConfigTab',['../da/df3/struct_i_config_tab.html',1,'']]],
  ['iconfiguration_7',['IConfiguration',['../d7/db4/struct_i_configuration.html',1,'']]],
  ['iconfigurationmock_8',['IConfigurationMock',['../d7/de5/class_i_configuration_mock.html',1,'']]],
  ['icorefactoryaccessor_9',['ICoreFactoryAccessor',['../d5/da9/struct_i_core_factory_accessor.html',1,'']]],
  ['icorefactoryaccessormock_10',['ICoreFactoryAccessorMock',['../d8/df8/class_i_core_factory_accessor_mock.html',1,'']]],
  ['id_11',['Id',['../db/dfb/class_id.html',1,'']]],
  ['id_3c_20int_2c_20struct_20database_5ftag_20_3e_12',['Id&lt; int, struct database_tag &gt;',['../db/dfb/class_id.html',1,'']]],
  ['id_3c_20int_2c_20struct_20person_5ftag_20_3e_13',['Id&lt; int, struct person_tag &gt;',['../db/dfb/class_id.html',1,'']]],
  ['id_3c_20int_2c_20struct_20photo_5ftag_20_3e_14',['Id&lt; int, struct photo_tag &gt;',['../db/dfb/class_id.html',1,'']]],
  ['id_3c_20int_2c_20struct_20photo_5ftag_20_3e_3c_20int_2c_20struct_20photo_5ftag_20_3e_15',['Id&lt; int, struct photo_tag &gt;&lt; int, struct photo_tag &gt;',['../db/dfb/class_id.html',1,'']]],
  ['id_3c_20int_2c_20struct_20photo_5ftag_20_3e_3c_20qlonglong_2c_20phash_5ftag_20_3e_16',['Id&lt; int, struct photo_tag &gt;&lt; qlonglong, phash_tag &gt;',['../db/dfb/class_id.html',1,'']]],
  ['idatabase_17',['IDatabase',['../d7/da9/struct_database_1_1_i_database.html',1,'Database']]],
  ['idatabasethread_18',['IDatabaseThread',['../d4/d9f/struct_database_1_1_i_database_thread.html',1,'Database']]],
  ['idcomparer_19',['IdComparer',['../d1/d1b/struct_database_1_1_memory_backend_1_1_id_comparer.html',1,'Database::MemoryBackend']]],
  ['idhash_20',['IdHash',['../d1/dc6/struct_photo_1_1_id_hash.html',1,'Photo']]],
  ['idtodataconverter_21',['IdToDataConverter',['../df/d55/class_id_to_data_converter.html',1,'']]],
  ['iexifreader_22',['IExifReader',['../d5/dd5/struct_i_exif_reader.html',1,'']]],
  ['iexifreaderfactory_23',['IExifReaderFactory',['../db/d10/struct_i_exif_reader_factory.html',1,'']]],
  ['ifeaturesmanager_24',['IFeaturesManager',['../d1/db4/class_i_features_manager.html',1,'']]],
  ['ifilenotifier_25',['IFileNotifier',['../d2/db5/struct_i_file_notifier.html',1,'']]],
  ['ifilesystemscanner_26',['IFileSystemScanner',['../dc/daa/struct_i_file_system_scanner.html',1,'']]],
  ['igenericsqlquerygenerator_27',['IGenericSqlQueryGenerator',['../d1/d71/struct_database_1_1_i_generic_sql_query_generator.html',1,'Database']]],
  ['igroupoperator_28',['IGroupOperator',['../d8/d5e/struct_database_1_1_i_group_operator.html',1,'Database']]],
  ['iinternal_29',['IInternal',['../d5/de9/struct_media_preview_1_1_i_internal.html',1,'MediaPreview']]],
  ['ilogger_30',['ILogger',['../df/ddd/struct_i_logger.html',1,'']]],
  ['iloggerfactory_31',['ILoggerFactory',['../d1/d78/struct_i_logger_factory.html',1,'']]],
  ['iloggerfactorymock_32',['ILoggerFactoryMock',['../d6/d74/class_i_logger_factory_mock.html',1,'']]],
  ['imagefile_33',['ImageFile',['../d6/d7e/struct_image_file.html',1,'']]],
  ['imagemediainformation_34',['ImageMediaInformation',['../de/d2a/class_image_media_information.html',1,'']]],
  ['imediainformation_35',['IMediaInformation',['../d4/d3a/struct_i_media_information.html',1,'']]],
  ['imedianotification_36',['IMediaNotification',['../d2/d3e/struct_i_media_notification.html',1,'']]],
  ['imodelcompositordatasource_37',['IModelCompositorDataSource',['../d2/d8b/class_i_model_compositor_data_source.html',1,'']]],
  ['impl_38',['Impl',['../db/d51/struct_database_1_1_builder_1_1_impl.html',1,'Database::Builder::Impl'],['../dc/d73/struct_database_1_1_memory_backend_1_1_impl.html',1,'Database::MemoryBackend::Impl'],['../d2/d03/struct_media_information_1_1_impl.html',1,'MediaInformation::Impl'],['../d0/d73/struct_photo_crawler_1_1_impl.html',1,'PhotoCrawler::Impl'],['../d3/d69/struct_plugin_loader_1_1_impl.html',1,'PluginLoader::Impl']]],
  ['inotifications_39',['INotifications',['../d2/d43/class_i_notifications.html',1,'']]],
  ['insertquerydata_40',['InsertQueryData',['../d4/df7/class_database_1_1_insert_query_data.html',1,'Database']]],
  ['internaltaskexecutor_41',['InternalTaskExecutor',['../dc/d3f/struct_internal_task_executor.html',1,'']]],
  ['inttask_42',['IntTask',['../d6/d86/struct_tasks_queue_1_1_int_task.html',1,'TasksQueue']]],
  ['ipeopleinformationaccessor_43',['IPeopleInformationAccessor',['../d1/d8a/class_database_1_1_i_people_information_accessor.html',1,'Database']]],
  ['iphotochangelogoperator_44',['IPhotoChangeLogOperator',['../db/d6b/struct_database_1_1_i_photo_change_log_operator.html',1,'Database']]],
  ['iphotocrawler_45',['IPhotoCrawler',['../d2/d0f/struct_i_photo_crawler.html',1,'']]],
  ['iphotooperator_46',['IPhotoOperator',['../d1/d7e/struct_database_1_1_i_photo_operator.html',1,'Database']]],
  ['iplugin_47',['IPlugin',['../d9/d56/struct_database_1_1_i_plugin.html',1,'Database']]],
  ['ipluginloader_48',['IPluginLoader',['../d5/d64/struct_i_plugin_loader.html',1,'']]],
  ['iprogressbar_49',['IProgressBar',['../de/d2f/struct_i_progress_bar.html',1,'']]],
  ['iprojectmanager_50',['IProjectManager',['../d7/dc8/class_i_project_manager.html',1,'']]],
  ['is_5fcopy_5fconstructible_3c_20testing_3a_3ainternal_3a_3areferenceorvaluewrapper_3c_20std_3a_3aoptional_3c_20std_3a_3aany_20_3e_20_3e_20_3e_51',['is_copy_constructible&lt; testing::internal::ReferenceOrValueWrapper&lt; std::optional&lt; std::any &gt; &gt; &gt;',['../dc/dab/structstd_1_1is__copy__constructible_3_01testing_1_1internal_1_1_reference_or_value_wrapper_3_01952bde62fea2a36d77a2dd0efe5f17be.html',1,'std']]],
  ['isqlqueryexecutor_52',['ISqlQueryExecutor',['../d9/d1b/struct_database_1_1_i_sql_query_executor.html',1,'Database']]],
  ['itaginfocollector_53',['ITagInfoCollector',['../de/d63/struct_i_tag_info_collector.html',1,'']]],
  ['itagsoperator_54',['ITagsOperator',['../d6/da5/struct_i_tags_operator.html',1,'']]],
  ['itask_55',['ITask',['../d6/d56/struct_database_1_1_i_database_thread_1_1_i_task.html',1,'Database::IDatabaseThread::ITask'],['../dd/d9b/struct_i_task_executor_1_1_i_task.html',1,'ITaskExecutor::ITask']]],
  ['itaskexecutor_56',['ITaskExecutor',['../d5/d45/struct_i_task_executor.html',1,'']]],
  ['itasksview_57',['ITasksView',['../d6/d44/struct_i_tasks_view.html',1,'']]],
  ['ithumbnailscache_58',['IThumbnailsCache',['../d7/ddf/struct_i_thumbnails_cache.html',1,'']]],
  ['ithumbnailsgenerator_59',['IThumbnailsGenerator',['../df/d64/class_i_thumbnails_generator.html',1,'']]],
  ['ithumbnailsmanager_60',['IThumbnailsManager',['../dd/dfb/struct_i_thumbnails_manager.html',1,'']]],
  ['itmpdir_61',['ITmpDir',['../d3/dc3/struct_i_tmp_dir.html',1,'']]],
  ['itransaction_62',['ITransaction',['../d3/de0/class_database_1_1_i_transaction.html',1,'Database']]],
  ['iupdater_63',['IUpdater',['../df/dcf/struct_i_updater.html',1,'']]],
  ['iviewtask_64',['IViewTask',['../da/d69/struct_i_view_task.html',1,'']]]
];
