
#define MAIN_ICO_PATH @CMAKE_CURRENT_BINARY_DIR@/main_ico.ico
#define VER_MAJOR @PROJECT_VERSION_MAJOR@
#define VER_MINOR @PROJECT_VERSION_MINOR@
#define VER_PATCH @PROJECT_VERSION_PATCH@
#define VER_FULL "@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"
