Microsoft Windows build:
	1. Visual studio.
		Visual Studio 2013 at least is required with Visual C++ Compiler Nov 2013 CTP (CTP_Nov2013) (due to c++11).
		QT 5.3 (first one with support for Visual Studio 2013)

